########################################################################## 3.6.2
library(gapminder)
names(gapminder)
lm.fit = lm(lifeExp ~ gdpPercap, data = gapminder)
attach(gapminder)
lm.fit = lm(lifeExp ~ gdpPercap)
lm.fit
summary(lm.fit)
names(lm.fit)
coef(lm.fit)
confint(lm.fit)
predict(lm.fit, data.frame(lifeExp = c(5, 10, 15)), interval = "confidence")
par("mar")
par(mar = c(1, 1, 1, 1))
predict(lm.fit, data.frame(lifeExp = c(5, 10, 15)), interval = "prediction")
plot(lstat, medv)
abline(lm.fit)
abline(lm.fit, lwd = 3)
abline(lm.fit, lwd = 3, col = "red")
plot(lstat, medv, col = "red")
plot(lstat, medv, pch = 20)
plot(lstat, medv, pch = "+")
plot(1:20, 1:20, pch = 1:20)
plot(1:20, 1:20, pch = 1:20)
par(mfrow = c(2,2))
plot(lm.fit)
plot(predict(lm.fit), residuals(lm.fit))
plot(predict(lm.fit), rstudent(lm.fit))
plot(hatvalues(lm.fit))
which.max(hatvalues(lm.fit))
########################################################################## 3.6.3
lm.fit=lm(lifeExp ~ gdpPercap + pop, data = gapminder)
summary(lm.fit)
vif(lm.fit)
lm.fit1 = lm(lifeExp~.-pop, data = gapminder)
summary(lm.fit1)
lm.fit1 = update(lm.fit, ~.-pop)
summary(lm(lifeExp~pop*gdpPercap, data = gapminder))
lm.fit2 = lm(lifeExp~gdpPercap + I(gdpPercap ^ 2))
summary(lm.fit2)
lm.fit = lm(lifeExp ~ gdpPercap)
anova(lm.fit, lm.fit2)
par(mfrow = c(2,2))
plot(lm.fit2)
lm.fit5 = lm(lifeExp~poly(gdpPercap, 5))
summary(lm.fit5)
summary(lm(lifeExp~log(pop), data = gapminder))
###########################################################################3.6.6
names(gapminder)
lm.fit = lm(Sales~.+ Income : Advertising + Price:Age, data = Carseats)
summary(lm.fit)
attach(Carseats)
contrasts(ShelveLoc)

LoadLibraries = function () {
  library(ggplot2)
  library(pander)
  print("The libraries have been loaded")
}
